extends Node
## Autoload: sound effects. Real CC0 samples from `assets/audio/` where they exist, with the old
## runtime synthesis as the fallback for anything missing, so the game never loses a sound.
## play() for one-shots at a position, loop_player() for engine / boost / weather loops the caller
## owns and pitches. Names with several samples pick a random take each time, so a rifle burst or
## a street of footsteps never repeats the same file twice in a row.

## Overall trim on every sound, in dB. Turn the whole game's SFX up or down here.
@export var master_volume_db: float = 0.0
## Random pitch spread on each one-shot (0.06 = +/- 6%) so repeats never sound identical.
@export var pitch_variation: float = 0.06
## How far a one-shot can still be heard, in metres.
@export var max_distance: float = 220.0
## Loudness falloff scale for one-shots: bigger carries further before it fades.
@export var unit_size: float = 12.0
## How far a loop (engine, boost, rain) can still be heard, in metres.
@export var loop_max_distance: float = 120.0
## Loudness falloff scale for loops.
@export var loop_unit_size: float = 10.0
## One-shot players: this many sounds can overlap before the oldest is cut off. Read at startup.
@export var pool_size: int = 24
## Set false to ignore assets/audio/ and use the synthesized sounds instead (to A/B the samples).
@export var use_samples: bool = true

const MIX_RATE := 22050
const AUDIO_DIR := "res://assets/audio/"

## Real recordings, all CC0. Every name here also has a synthesized fallback below, so a missing
## or unimported file degrades to the old sound rather than to silence.
const SAMPLES := {
	"shot": ["shot_0.ogg", "shot_1.ogg", "shot_2.ogg"],
	"explosion": ["explosion_0.ogg", "explosion_1.ogg"],
	"rocket": ["rocket_0.ogg"],
	"break": ["break_0.ogg", "break_1.ogg", "break_2.ogg"],
	"glass": ["glass_0.ogg", "glass_1.ogg", "glass_2.ogg"],
	"crash": ["crash_0.ogg", "crash_1.ogg", "crash_2.ogg"],
	"land": ["land_0.ogg", "land_1.ogg"],
	"thud": ["thud_0.ogg", "thud_1.ogg"],
	"footstep": ["footstep_0.ogg", "footstep_1.ogg", "footstep_2.ogg",
		"footstep_3.ogg", "footstep_4.ogg", "footstep_5.ogg"],
	"horn": ["horn_0.ogg"],
	"engine_loop": ["engine_loop_0.ogg"],
	"boost_loop": ["boost_loop_0.ogg"],
	"rain": ["rain_0.ogg"],
	"wind": ["wind_0.ogg"],
	"ambience_city": ["ambience_city_0.ogg"],
	"thunder": ["thunder_0.ogg"],
}

## Sample names that have to loop. Set on the stream in code rather than in the .import file, so
## an .import regenerated by the editor can never silently drop the loop flag.
const LOOPING := ["engine_loop", "boost_loop", "rain", "wind", "ambience_city", "skid"]

var _streams: Dictionary = {}
var _pool: Array[AudioStreamPlayer3D] = []
var _next: int = 0
var _rng := RandomNumberGenerator.new()


func _ready() -> void:
	_rng.seed = 1
	_build_synth()
	if use_samples:
		_load_samples()
	for i in maxi(pool_size, 1):
		var p := AudioStreamPlayer3D.new()
		p.max_distance = max_distance
		p.unit_size = unit_size
		add_child(p)
		_pool.append(p)


func has(name: String) -> bool:
	var takes: Array = _streams.get(name, [])
	return not takes.is_empty()


func play(name: String, at: Vector3, volume_db: float = 0.0, pitch: float = 1.0) -> void:
	var stream := _pick(name)
	if stream == null or _pool.is_empty():
		return
	var p := _pool[_next]
	_next = (_next + 1) % _pool.size()
	p.stop()
	p.stream = stream
	p.global_position = at
	p.volume_db = volume_db + master_volume_db
	p.pitch_scale = pitch * _rng.randf_range(1.0 - pitch_variation, 1.0 + pitch_variation)
	p.play()


## A looping player for the caller to parent and control.
func loop_player(name: String, volume_db: float = -6.0) -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	var takes: Array = _streams.get(name, [])
	if not takes.is_empty():
		p.stream = takes[0]
	p.volume_db = volume_db + master_volume_db
	p.max_distance = loop_max_distance
	p.unit_size = loop_unit_size
	return p


## One random take of a sound, or null if the name is unknown.
func _pick(key: String) -> AudioStream:
	var takes: Array = _streams.get(key, [])
	if takes.is_empty():
		return null
	if takes.size() == 1:
		return takes[0]
	return takes[_rng.randi() % takes.size()]


# --- Samples -----------------------------------------------------------------------------

func _load_samples() -> void:
	for key: String in SAMPLES:
		var takes: Array[AudioStream] = []
		for file_name: String in SAMPLES[key]:
			var path := AUDIO_DIR + file_name
			if not ResourceLoader.exists(path):
				continue
			var stream := ResourceLoader.load(path) as AudioStream
			if stream == null:
				continue
			if key in LOOPING:
				_set_looping(stream)
			takes.append(stream)
		if not takes.is_empty():
			_streams[key] = takes # real takes replace the synthesized fallback


func _set_looping(stream: AudioStream) -> void:
	if stream is AudioStreamOggVorbis:
		var ogg := stream as AudioStreamOggVorbis
		ogg.loop = true
		ogg.loop_offset = 0.0


# --- Synthesis (fallback) ----------------------------------------------------------------

func _build_synth() -> void:
	_put("shot", _noise_burst(0.10, 40.0, 0.9, 0.35))
	_put("rocket", _noise_burst(0.35, 9.0, 0.7, 0.08))
	_put("explosion", _noise_burst(1.3, 3.5, 1.0, 0.03))
	_put("grab", _sweep(0.22, 220.0, 900.0, 0.5))
	_put("launch", _sweep(0.25, 900.0, 200.0, 0.7))
	_put("jump", _sweep(0.16, 320.0, 640.0, 0.45))
	_put("land", _thud(0.12, 90.0, 0.7))
	_put("thud", _thud(0.18, 70.0, 0.9))
	_put("footstep", _thud(0.07, 140.0, 0.4))
	_put("break", _noise_burst(0.28, 14.0, 0.8, 0.2))
	_put("glass", _noise_burst(0.34, 11.0, 0.7, 0.75))
	_put("crash", _noise_burst(0.45, 8.0, 1.0, 0.15))
	_put("horn", _horn(0.5))
	_put("yelp", _yelp(0.4))
	_put("click", _sweep(0.05, 1200.0, 900.0, 0.4))
	_put("boost_loop", _boost_loop(0.6), true)
	_put("engine_loop", _engine_loop(0.4), true)
	_put("skid", _skid_loop(0.5), true)
	_put("rain", _rain_loop(1.5), true)
	_put("wind", _wind_loop(2.0), true)
	_put("ambience_city", _city_loop(2.0), true)
	_put("thunder", _thunder(3.2))


func _put(key: String, samples: PackedFloat32Array, looping: bool = false) -> void:
	var takes: Array[AudioStream] = [_wav(samples, looping)]
	_streams[key] = takes


func _wav(samples: PackedFloat32Array, looping: bool = false) -> AudioStreamWAV:
	var wav := AudioStreamWAV.new()
	wav.format = AudioStreamWAV.FORMAT_16_BITS
	wav.mix_rate = MIX_RATE
	wav.stereo = false
	var bytes := PackedByteArray()
	bytes.resize(samples.size() * 2)
	for i in samples.size():
		var v := int(clampf(samples[i], -1.0, 1.0) * 32767.0)
		bytes.encode_s16(i * 2, v)
	wav.data = bytes
	if looping:
		wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
		wav.loop_begin = 0
		wav.loop_end = samples.size()
	return wav


func _noise_burst(seconds: float, decay: float, gain: float, smooth: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		var white := _rng.randf_range(-1.0, 1.0)
		last = lerpf(last, white, smooth) # low-pass: smaller smooth = deeper rumble
		out[i] = last * exp(-decay * t) * gain * 3.0
	return out


func _sweep(seconds: float, f0: float, f1: float, gain: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var phase := 0.0
	for i in n:
		var t := float(i) / n
		var f := lerpf(f0, f1, t)
		phase += TAU * f / MIX_RATE
		var env := sin(t * PI)
		out[i] = sin(phase) * env * gain
	return out


func _thud(seconds: float, f: float, gain: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	for i in n:
		var t := float(i) / MIX_RATE
		out[i] = sin(TAU * f * t * (1.0 - t * 2.0)) * exp(-18.0 * t) * gain
	return out


func _yelp(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var phase := 0.0
	for i in n:
		var t := float(i) / n
		var f := lerpf(750.0, 280.0, t * t) * (1.0 + 0.06 * sin(t * 60.0))
		phase += TAU * f / MIX_RATE
		var env := minf(t * 12.0, 1.0) * (1.0 - t)
		out[i] = (sin(phase) * 0.7 + sin(phase * 2.0) * 0.3) * env * 0.6
	return out


## Two detuned tones a major third apart, which is roughly what a car horn is.
func _horn(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	for i in n:
		var t := float(i) / MIX_RATE
		var env := minf(t * 60.0, 1.0) * minf((seconds - t) * 40.0, 1.0)
		var a := sin(TAU * 440.0 * t)
		var b := sin(TAU * 554.0 * t)
		var buzz := sin(TAU * 880.0 * t) * 0.2 + sin(TAU * 1108.0 * t) * 0.15
		out[i] = (a * 0.4 + b * 0.35 + buzz) * env * 0.6
	return out


func _boost_loop(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		last = lerpf(last, _rng.randf_range(-1.0, 1.0), 0.12)
		out[i] = last * 0.5 + sin(TAU * 110.0 * t) * 0.15 + sin(TAU * 220.0 * t) * 0.08
	return out


func _engine_loop(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	for i in n:
		var t := float(i) / MIX_RATE
		var saw := fmod(t * 55.0, 1.0) * 2.0 - 1.0
		out[i] = saw * 0.25 + sin(TAU * 110.0 * t) * 0.2 + sin(TAU * 165.0 * t) * 0.08
	return out


## Tyre skid: band-limited noise with a resonant squeal riding on top. No CC0 recording of a
## skid was found, so this one has no sample behind it.
func _skid_loop(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	var band := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		last = lerpf(last, _rng.randf_range(-1.0, 1.0), 0.6)
		band = lerpf(band, last, 0.25) # a second pole: leaves a narrow noise band
		var squeal := sin(TAU * (1250.0 + 90.0 * sin(TAU * 7.0 * t)) * t)
		out[i] = (last - band) * 0.8 + squeal * 0.18
	return out


## Steady hiss of rain: low-passed white noise with a slow flutter.
func _rain_loop(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		last = lerpf(last, _rng.randf_range(-1.0, 1.0), 0.45)
		out[i] = last * 0.35 * (0.85 + 0.15 * sin(TAU * 0.7 * t))
	return out


## Wind: deeper than rain and gustier, so the level breathes over a few seconds.
func _wind_loop(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		last = lerpf(last, _rng.randf_range(-1.0, 1.0), 0.06)
		var gust := 0.7 + 0.3 * sin(TAU * t / seconds) # one whole gust per loop, so it seams
		out[i] = last * 2.2 * gust
	return out


## Distant traffic: a low rumble with a slow swell, enough to keep a street from sounding dead.
func _city_loop(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		last = lerpf(last, _rng.randf_range(-1.0, 1.0), 0.03)
		var swell := 0.75 + 0.25 * sin(TAU * t / seconds)
		out[i] = last * 3.0 * swell + sin(TAU * 62.0 * t) * 0.03
	return out


## Thunder: a deep rumble that cracks first, then rolls off.
func _thunder(seconds: float) -> PackedFloat32Array:
	var n := int(seconds * MIX_RATE)
	var out := PackedFloat32Array()
	out.resize(n)
	var last := 0.0
	for i in n:
		var t := float(i) / MIX_RATE
		last = lerpf(last, _rng.randf_range(-1.0, 1.0), 0.02 + 0.2 * exp(-8.0 * t))
		var env := exp(-1.4 * t) * (1.0 + 0.5 * sin(TAU * 2.3 * t) * exp(-t))
		out[i] = clampf(last * 6.0 * env, -1.0, 1.0)
	return out
