class_name BillboardTable
## GENERATED by tools/make_billboard_art.py - do not edit. The LINEAR mean colour of every
## cell of assets/textures/billboards/billboard_ads.jpg, for the far boxes (Billboards.far_color()).

const BULLETIN_MEAN: Array[Color] = [Color(0.1079, 0.1398, 0.2028), Color(0.6768, 0.2973, 0.1679), Color(0.0727, 0.0501, 0.0643), Color(0.5172, 0.3254, 0.0072), Color(0.0334, 0.0852, 0.0166), Color(0.2221, 0.0996, 0.0694), Color(0.3028, 0.4143, 0.6323), Color(0.1221, 0.2099, 0.1894), Color(0.0585, 0.0607, 0.1043), Color(0.4208, 0.4020, 0.4246), Color(0.3581, 0.0885, 0.3137), Color(0.0290, 0.0223, 0.0214)]
const POSTER_MEAN: Array[Color] = [Color(0.0967, 0.1257, 0.1859), Color(0.7142, 0.2466, 0.1193), Color(0.0803, 0.0429, 0.0558), Color(0.5000, 0.3148, 0.0110), Color(0.0304, 0.0668, 0.0184), Color(0.1775, 0.0737, 0.0535), Color(0.3414, 0.4476, 0.6542), Color(0.0991, 0.2029, 0.1734), Color(0.0714, 0.0756, 0.1194), Color(0.4319, 0.4179, 0.4413), Color(0.3356, 0.0566, 0.2897), Color(0.0227, 0.0173, 0.0157)]
const PORTRAIT_MEAN: Array[Color] = [Color(0.6916, 0.2100, 0.1056), Color(0.5583, 0.3482, 0.0103), Color(0.1857, 0.0933, 0.0624), Color(0.0344, 0.0659, 0.0240), Color(0.3876, 0.4812, 0.6664), Color(0.4748, 0.4636, 0.6112)]
const NAMES: Array[String] = ["the_last_orbit", "fizzly", "lumen_x", "ramirez_kolb", "zapwolf", "sand_and_smoke", "suncrest_air", "stardust_drive_in", "casa_lunara", "corvo_aria", "drift_104", "hollow_house"]
const PORTRAIT_NAMES: Array[String] = ["fizzly", "ramirez_kolb", "sand_and_smoke", "zapwolf", "suncrest_air", "stride_co"]
